#Mini Assignment 6. Data Cleaning & Preparation
Please add one code cell after each question and create a program to answer the question. Make sure your code runs without error. After you are finished, click on File -> Print -> Save as PDF to create a PDF output and upload it on Brightspace.

NOTE: Make sure your PDF does not have your name or any identifying information in the name or content of the file. Anonymity is essential for the peer-review process.

##Data Ingestion & Cleaning

1. Ingest [the Census 2017 dataset](https://drive.google.com/file/d/1bXZmQVLq0bG29mmIhsQneXUzCQ20Qpaj/view?usp=sharing) into a dataframe. Make sure string like ‘na’ and ‘NA’ are identified as missing values. Then check out the first few rows, descriptive statistics, and data type for each column of the dataset.

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('cns2017_county_data.csv', na_values=['na', 'NA'])
df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899.0,28137.0,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112.0,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527.0,103833.0,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527.0,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976.0,12225.0,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878.0,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251.0,10329.0,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171.0,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490.0,29177.0,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380.0,83.9,11.9,4.0,0.1,4.9

In [ ]:
df.describe()

           CountyId      TotalPop  IncomePerCap  IncomePerCapErr
count   3220.000000  3.220000e+03   3220.000000      3220.000000
mean   31393.605280  1.007681e+05  25657.033230      1514.442547
std    16292.078954  3.244996e+05   6667.520452      1156.708587
min     1001.000000  7.400000e+01   5943.000000       129.000000
25%    19032.500000  1.121350e+04  21568.000000       832.000000
50%    30024.000000  2.584750e+04  25139.000000      1225.000000
75%    46105.500000  6.660825e+04  28997.000000      1802.500000
max    72153.000000  1.010572e+07  69529.000000     16145.000000

In [ ]:
df.dtypes

CountyId              int64
State                object
County               object
TotalPop              int64
Men                 float64
Women               float64
Hispanic            float64
White               float64
Black               float64
Native              float64
Asian               float64
Pacific             float64
VotingAgeCitizen    float64
Income              float64
IncomeErr           float64
IncomePerCap          int64
IncomePerCapErr       int64
Poverty             float64
ChildPoverty        float64
Professional        float64
Service             float64
Office              float64
Construction        float64
Production          float64
Drive               float64
Carpool             float64
Transit             float64
Walk                float64
OtherTransp         float64
WorkAtHome          float64
MeanCommute         float64
Employed            float64
PrivateWork         float64
PublicWork          float64
SelfEmployed        float64
FamilyWork          float64
Unemployment        float64
dtype: object

2. Check if there are any duplicate records (rows). How many duplicate records are there?

In [ ]:
duplicate_records = df.duplicated()
duplicate_records.sum()
#there are no duplicate records

0

3. Display the ratio (in percentage) of missing values for each column. Then drop any column that has over 50% of missing values. Next, do the same for the rows; meaning drop the rows with over 50% missing values. Display the number of rows before and after you drop such rows.

In [ ]:
#show missing percentage for columns
missing_col_percentage = df.isnull().mean()*100
missing_col_percentage

CountyId            0.000000
State               0.000000
County              0.000000
TotalPop            0.000000
Men                 0.062112
Women               0.062112
Hispanic            0.217391
White               0.217391
Black               0.217391
Native              0.248447
Asian               0.217391
VotingAgeCitizen    0.062112
Income              0.062112
IncomeErr           0.062112
IncomePerCap        0.000000
IncomePerCapErr     0.000000
Poverty             0.124224
ChildPoverty        0.186335
Professional        0.155280
Service             0.155280
Office              0.217391
Construction        0.186335
Production          0.155280
Drive               0.093168
Carpool             0.186335
Walk                0.279503
OtherTransp         0.310559
WorkAtHome          0.217391
MeanCommute         0.155280
Employed            0.062112
PrivateWork         0.093168
PublicWork          0.217391
SelfEmployed        0.279503
FamilyWork          0.372671
Unemployment        0.186335
dtype: float64

In [ ]:
#drop columns with more than 50% NA values
df = df.loc[:, missing_col_percentage <= 0.5]
df.columns
#removed 'Pacific' and 'Transit' columns that were >50%

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'VotingAgeCitizen', 'Income',
       'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Walk', 'OtherTransp', 'WorkAtHome',
       'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork', 'SelfEmployed',
       'FamilyWork', 'Unemployment'],
      dtype='object')

In [ ]:
#missing rows
missing_row_percentage = df.isnull().mean(axis=1)*100
missing_row_percentage

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
3215    0.0
3216    0.0
3217    0.0
3218    0.0
3219    0.0
Length: 3220, dtype: float64

In [ ]:
df.shape[0]

3220

In [ ]:
#drop missing rows
df = df.loc[missing_row_percentage <=0.5]
df.shape[0]
#dropped 38 rows

3182

4. For the remaining missing values in the dataframe, fill them all with the median value of its column.

In [ ]:
df = df.fillna(df.median(numeric_only=True))
df

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899.0,28137.0,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112.0,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527.0,103833.0,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527.0,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976.0,12225.0,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878.0,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251.0,10329.0,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171.0,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490.0,29177.0,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380.0,83.9,11.9,4.0,0.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Puerto Rico,Vega Baja Municipio,54754,26269.0,28485.0,96.7,3.1,0.1,0.0,...,1.4,0.6,0.9,31.6,14234.0,76.2,19.3,4.3,0.2,16.8
3216,72147,Puerto Rico,Vieques Municipio,8931,4351.0,4580.0,95.7,4.0,0.0,0.0,...,5.0,0.0,1.7,14.9,2927.0,40.7,40.9,18.4,0.0,12.8
3217,72149,Puerto Rico,Villalba Municipio,23659,11510.0,12149.0,99.7,0.2,0.1,0.0,...,2.1,0.0,2.8,28.4,6873.0,59.2,30.2,10.4,0.2,24.8
3218,72151,Puerto Rico,Yabucoa Municipio,35025,16984.0,18041.0,99.9,0.1,0.0,0.0,...,1.4,1.8,0.1,30.5,7878.0,62.7,30.9,6.3,0.0,25.4
3219,72153,Puerto Rico,Yauco Municipio,37585,18052.0,19533.0,99.8,0.2,0.0,0.0,...,1.7,0.1,5.0,24.4,8995.0,66.4,28.7,5.0,0.0,24.0

## Data Preparation

5. Encode the state names using label encoding, and store the encoded column in a new column called 'state_coded'.

In [ ]:
df['State'] = df['State'].astype('category')

In [ ]:
df['state_coded'] = df['State'].cat.codes

In [ ]:
df

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment,state_coded
0,1001,Alabama,Autauga County,55036,26899.0,28137.0,2.7,75.4,18.9,0.3,...,1.3,2.5,25.8,24112.0,74.1,20.2,5.6,0.1,5.2,0
1,1003,Alabama,Baldwin County,203360,99527.0,103833.0,4.4,83.1,9.5,0.8,...,1.1,5.6,27.0,89527.0,80.7,12.9,6.3,0.1,5.5,0
2,1005,Alabama,Barbour County,26201,13976.0,12225.0,4.2,45.7,47.8,0.2,...,1.7,1.3,23.4,8878.0,74.1,19.1,6.5,0.3,12.4,0
3,1007,Alabama,Bibb County,22580,12251.0,10329.0,2.4,74.6,22.0,0.4,...,1.7,1.5,30.0,8171.0,76.0,17.4,6.3,0.3,8.2,0
4,1009,Alabama,Blount County,57667,28490.0,29177.0,9.0,87.4,1.5,0.3,...,0.4,2.1,35.0,21380.0,83.9,11.9,4.0,0.1,4.9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Puerto Rico,Vega Baja Municipio,54754,26269.0,28485.0,96.7,3.1,0.1,0.0,...,0.6,0.9,31.6,14234.0,76.2,19.3,4.3,0.2,16.8,39
3216,72147,Puerto Rico,Vieques Municipio,8931,4351.0,4580.0,95.7,4.0,0.0,0.0,...,0.0,1.7,14.9,2927.0,40.7,40.9,18.4,0.0,12.8,39
3217,72149,Puerto Rico,Villalba Municipio,23659,11510.0,12149.0,99.7,0.2,0.1,0.0,...,0.0,2.8,28.4,6873.0,59.2,30.2,10.4,0.2,24.8,39
3218,72151,Puerto Rico,Yabucoa Municipio,35025,16984.0,18041.0,99.9,0.1,0.0,0.0,...,1.8,0.1,30.5,7878.0,62.7,30.9,6.3,0.0,25.4,39
3219,72153,Puerto Rico,Yauco Municipio,37585,18052.0,19533.0,99.8,0.2,0.0,0.0,...,0.1,5.0,24.4,8995.0,66.4,28.7,5.0,0.0,24.0,39

6. Bin the TotalPop column into six equally-sized bins, and store it as a new column called "TotalPop_bins".

In [ ]:
df['TotalPop_bins'] = pd.cut(df['TotalPop'], bins=6)
df['TotalPop_bins']

0       (-10031.648, 1684348.667]
1       (-10031.648, 1684348.667]
2       (-10031.648, 1684348.667]
3       (-10031.648, 1684348.667]
4       (-10031.648, 1684348.667]
                  ...
3215    (-10031.648, 1684348.667]
3216    (-10031.648, 1684348.667]
3217    (-10031.648, 1684348.667]
3218    (-10031.648, 1684348.667]
3219    (-10031.648, 1684348.667]
Name: TotalPop_bins, Length: 3182, dtype: category
Categories (6, interval[float64, right]): [(-10031.648, 1684348.667] < (1684348.667, 3368623.333] <
                                           (3368623.333, 5052898.0] < (5052898.0, 6737172.667] <
                                           (6737172.667, 8421447.333] < (8421447.333, 10105722.0]]